/**
 * Findings — Unified finding management centre.
 *
 * System design:
 *   • Every finding gets a stable external_id (AL-YYYY-NNNNN) generated by
 *     the backend on first insert and never changed.
 *   • All state mutations go to PATCH /api/v1/soc/findings/{id} which writes
 *     to the findings table and inserts a row into finding_activity for audit.
 *   • Bulk mutations go to POST /api/v1/soc/bulk.
 *   • localStorage mirrors last-known state for optimistic UI; cleared on
 *     every successful server sync.
 *   • Indexes: external_id (unique), severity, status, category, agent_id,
 *     sla_status, assignee, composite_score DESC, first_detected_at DESC.
 *
 * Case workflow:
 *   NEW → TRIAGING → INVESTIGATING → IN_REMEDIATION → CLOSED
 *                                                   → FALSE_POSITIVE
 *                                                   → ACCEPTED_RISK
 *                                                   → DUPLICATE
 *   Any closed state → REOPENED → back to TRIAGING
 */
import { useState, useEffect, useCallback, useRef } from "react";
import { useTimeRange } from "../context/TimeRangeContext";
import { useRefresh } from "../context/RefreshContext";
import { rangeToParams } from "../lib/timeRange";
import { createPortal } from "react-dom";
import {
  AlertTriangle, RefreshCw, CheckCircle2, XCircle, Shield,
  Clock, ChevronDown, ChevronRight, Filter, Search,
  MessageSquare, Activity, Copy, ExternalLink, Zap,
  User, Calendar, Tag, ArrowRight, RotateCcw, Hash,
  TrendingUp, FileText, GitBranch, Radio, Send,
  CheckSquare, Square, AlertCircle, Layers,
} from "lucide-react";
import { cn } from "../../lib/utils";
import { useRBAC } from "../context/RBACContext";
import {
  fmtTs,
  type DetectionFinding,
  AIPrecisionPanel,
  OSRemediationPanel,
  TerrainValidationPanel,
  AdvancedFilter,
  AgentSelect,
  applyAdvancedConditions,
  type FilterCondition,
} from "./DetectionShared";

const SOC = "/api/v1/soc";
export const VALIDATED_FINDINGS_URL = "/api/v1/detection/all";

type ValidatedView = "active" | "closed" | "all";

export function validatedFindingsQuery(view: ValidatedView): URLSearchParams {
  return new URLSearchParams({ view, validated_only: "true" });
}

export interface ValidationRecomputeProgress {
  job_uid: string;
  state: "queued" | "running" | "completed" | "cancelled" | "error";
  scanned: number;
  updated: number;
  histogram: Record<string, number>;
  error?: string;
}

export async function runValidationRecompute(
  request: typeof fetch = fetch,
  onProgress?: (progress: ValidationRecomputeProgress) => void,
): Promise<ValidationRecomputeProgress> {
  let response = await request(
    "/api/v1/settings/validation/recompute?batch_size=250",
    { method: "POST" },
  );
  if (!response.ok) throw new Error(`Recompute failed (${response.status})`);
  let progress = await response.json() as ValidationRecomputeProgress;
  onProgress?.(progress);
  for (let batches = 0; progress.state === "running" && batches < 400; batches++) {
    response = await request(
      `/api/v1/settings/validation/recompute/${progress.job_uid}/resume?batch_size=250`,
      { method: "POST" },
    );
    if (!response.ok) throw new Error(`Recompute resume failed (${response.status})`);
    progress = await response.json() as ValidationRecomputeProgress;
    onProgress?.(progress);
  }
  if (progress.state === "error") throw new Error(progress.error || "Recompute job failed");
  return progress;
}

// ── Types ─────────────────────────────────────────────────────────────────────

interface Finding extends DetectionFinding {
  status:          string;
  priority?:       number;
  assignee?:       string;
  analyst_notes?:  string;
  sla_due?:        number;
  sla_status?:     string;
  closed_at?:      number;
  external_id?:    string;
  display_id?:     string;
  tags?:           string | string[];
  // Threshold the AI Precision Validator resolved for this row's (agent, category).
  // Populated by /findings when ?validated_only=true.
  effective_threshold?: number;
}

interface ActivityEntry {
  action:    string;
  actor:     string;
  created_at:number;
  old_value: string;
  new_value: string;
  comment?:  string;
}

// ── System Design — Status & Category Config ──────────────────────────────────

const STATUS_FLOW: { key: string; label: string; badge: string; next: string[] }[] = [
  { key: "new",            label: "New",            badge: "bg-red-50 text-red-700 border-red-300",      next: ["triaging","false_positive","duplicate"] },
  { key: "triaging",       label: "Triaging",       badge: "bg-amber-50 text-amber-700 border-amber-300",next: ["investigating","false_positive","accepted_risk","duplicate"] },
  { key: "investigating",  label: "Investigating",   badge: "bg-blue-50 text-blue-700 border-blue-300",   next: ["in_remediation","false_positive","accepted_risk","duplicate"] },
  { key: "in_remediation", label: "In Remediation", badge: "bg-purple-50 text-purple-700 border-purple-300", next: ["closed","false_positive"] },
  { key: "closed",         label: "Closed",         badge: "bg-green-50 text-green-700 border-green-300", next: ["new"] },
  { key: "false_positive", label: "False Positive", badge: "bg-gray-100 text-gray-500 border-gray-300",   next: ["new"] },
  { key: "accepted_risk",  label: "Accepted Risk",  badge: "bg-amber-50 text-amber-600 border-amber-300", next: ["new"] },
  { key: "duplicate",      label: "Duplicate",      badge: "bg-gray-100 text-gray-400 border-gray-200",   next: ["new"] },
];

const STATUS_MAP = Object.fromEntries(STATUS_FLOW.map(s => [s.key, s]));

const WORKFLOW_STEPS = ["new","triaging","investigating","in_remediation","closed"];

const CAT_CONFIG: Record<string, { label: string; color: string; dot: string; bg: string }> = {
  // Persistence terrain — execution paths, processes, containers, tasks, startup
  execution:      { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  malware:        { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  process:        { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  script:         { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  container:      { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  persistence:    { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  service:        { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  task:           { label: "Citadels",   color: "text-red-700",    dot: "bg-red-500",    bg: "bg-red-50 border-red-200"    },
  // Reachability terrain — network, ports, connections, shares
  network:        { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  connection:     { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  port:           { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  arp:            { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  covert:         { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  lateral:        { label: "Vector",  color: "text-blue-700",   dot: "bg-blue-500",   bg: "bg-blue-50 border-blue-200"  },
  // Surface terrain — apps, packages, SBOMs, configs, system components
  package:        { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  vulnerability:  { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  sbom:           { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  config:         { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  binary:         { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  sysctl:         { label: "Origin",       color: "text-amber-700",  dot: "bg-amber-500",  bg: "bg-amber-50 border-amber-200"},
  // Identity and Posture stay unchanged
  user:           { label: "Identity",      color: "text-indigo-700", dot: "bg-indigo-500", bg: "bg-indigo-50 border-indigo-200" },
  identity:       { label: "Identity",      color: "text-indigo-700", dot: "bg-indigo-500", bg: "bg-indigo-50 border-indigo-200" },
  account:        { label: "Identity",      color: "text-indigo-700", dot: "bg-indigo-500", bg: "bg-indigo-50 border-indigo-200" },
  security:       { label: "Posture",       color: "text-green-700",  dot: "bg-green-500",  bg: "bg-green-50 border-green-200" },
  posture:        { label: "Posture",       color: "text-green-700",  dot: "bg-green-500",  bg: "bg-green-50 border-green-200" },
};

const CAT_GROUPS = [
  { key: "all",        label: "All Findings" },
  { key: "surface",    label: "Origin"    },
  { key: "reach",      label: "Vector"    },
  { key: "persist",    label: "Citadels"  },
  { key: "user",       label: "Identity"     },
  { key: "security",   label: "Posture"      },
];

const PRIORITIES: Record<number, { label: string; color: string }> = {
  1: { label: "P1 · Critical",  color: "text-red-600"    },
  2: { label: "P2 · High",      color: "text-amber-600"  },
  3: { label: "P3 · Medium",    color: "text-blue-600"   },
  4: { label: "P4 · Low",       color: "text-green-600"  },
  5: { label: "P5 · Info",      color: "text-gray-400"   },
};

const SEV_DOT: Record<string, string> = {
  critical: "bg-red-500", high: "bg-amber-500",
  medium: "bg-blue-500",  low:  "bg-green-500", info: "bg-gray-300",
};
const SEV_BADGE: Record<string, string> = {
  critical: "bg-red-50 text-red-700 border-red-300",
  high:     "bg-amber-50 text-amber-700 border-amber-300",
  medium:   "bg-blue-50 text-blue-700 border-blue-300",
  low:      "bg-green-50 text-green-700 border-green-300",
  info:     "bg-gray-100 text-gray-500 border-gray-200",
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function relTime(ts: number): string {
  if (!ts) return "—";
  const s = Math.floor(Date.now() / 1000 - ts);
  if (s < 60)    return `${s}s ago`;
  if (s < 3600)  return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  return `${Math.floor(s / 86400)}d ago`;
}

function catKey(cat: string): string {
  const c = cat.toLowerCase();
  // Persistence terrain: execution paths, processes, containers, tasks, startup mechanisms
  if (c.includes("exec") || c.includes("malware") || c.includes("script") || c.includes("process") ||
      c.includes("persist") || c.includes("service") || c.includes("task") || c.includes("container") ||
      c.includes("lateral") || c.includes("covert")) return "persist";
  // Reachability terrain: network, ports, interfaces, shares, connections
  if (c.includes("network") || c.includes("connection") || c.includes("c2") || c.startsWith("feed") ||
      c.includes("port") || c.includes("arp") || c.includes("dns") || c.includes("tunnel")) return "reach";
  // Surface terrain: packages, SBOMs, configs, apps, system components
  if (c.includes("package") || c.includes("vuln") || c.includes("cve") || c.includes("sbom") ||
      c.includes("config") || c.includes("binary") || c.includes("sysctl") || c.includes("app")) return "surface";
  // Identity
  if (c.includes("user") || c.includes("identity") || c.includes("account") || c.includes("credential")) return "user";
  // Posture
  if (c.includes("security") || c.includes("posture") || c.includes("sip") || c.includes("firewall")) return "security";
  return c;
}

function catCfg(cat: string) { return CAT_CONFIG[catKey(cat)] ?? { label: cat, color: "text-gray-600", dot: "bg-gray-400", bg: "bg-gray-100 border-gray-200" }; }

function useCountUp(target: number): number {
  const [val, setVal] = useState(0);
  const ref = useRef(0);
  useEffect(() => {
    const diff = target - ref.current; const steps = 20; let i = 0;
    const t = setInterval(() => { i++; setVal(Math.round(ref.current + diff * (1 - Math.pow(1 - i/steps, 3)))); if (i >= steps) { clearInterval(t); ref.current = target; } }, 30);
    return () => clearInterval(t);
  }, [target]);
  return val;
}

function parseArr(v: unknown): string[] {
  if (Array.isArray(v)) return v as string[];
  if (typeof v === "string" && v.startsWith("[")) { try { return JSON.parse(v); } catch {} }
  return [];
}

// ── API ───────────────────────────────────────────────────────────────────────

async function patchFinding(id: number, body: Record<string, unknown>): Promise<boolean> {
  try { const r = await fetch(`${SOC}/findings/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return r.ok; }
  catch { return false; }
}

async function bulkAction(ids: number[], action: string, value?: string): Promise<boolean> {
  try { const r = await fetch(`${SOC}/bulk`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ finding_ids: ids, action, value, actor: "analyst" }) }); return r.ok; }
  catch { return false; }
}

// ── KPI tile ──────────────────────────────────────────────────────────────────

function KpiTile({ label, value, sub, color, bg, icon, delay }: {
  label: string; value: number; sub?: string;
  color: string; bg: string; icon: React.ReactNode; delay?: number;
}) {
  const count = useCountUp(value);
  return (
    <div className={cn("rounded-xl border p-3 text-center al-bounce-in", bg)} style={{ animationDelay: `${delay ?? 0}ms` }}>
      <div className="flex justify-center mb-1 opacity-60">{icon}</div>
      <div className={cn("text-xl font-black tabular-nums leading-none", color)}>{count}</div>
      <div className="text-[9px] text-gray-500 font-semibold mt-1">{label}</div>
      {sub && <div className="text-[8px] text-gray-400 mt-0.5">{sub}</div>}
    </div>
  );
}

// ── Status workflow strip ─────────────────────────────────────────────────────

function WorkflowStrip({ current }: { current: string }) {
  const idx = WORKFLOW_STEPS.indexOf(current);
  return (
    <div className="flex items-center gap-0">
      {WORKFLOW_STEPS.map((step, i) => {
        const isPast    = i < idx;
        const isCurrent = i === idx;
        const label = STATUS_MAP[step]?.label ?? step;
        return (
          <div key={step} className="flex items-center">
            <div className={cn(
              "px-2.5 py-1 text-[9px] font-bold rounded-full border transition-all",
              isCurrent ? "bg-orange-500 text-white border-orange-500 shadow-sm" :
              isPast    ? "bg-green-50 text-green-600 border-green-200" :
              "bg-gray-50 text-gray-400 border-gray-200"
            )}>
              {isPast && <span className="mr-0.5">✓</span>}{label}
            </div>
            {i < WORKFLOW_STEPS.length - 1 && (
              <ArrowRight className={cn("w-3 h-3 mx-0.5 flex-shrink-0", isPast ? "text-green-400" : "text-gray-200")} />
            )}
          </div>
        );
      })}
    </div>
  );
}

// ── Finding detail drawer (fixed right-side overlay) ─────────────────────────

type DetailTab = "overview" | "case" | "timeline";

const SEV_STRIPE: Record<string, string> = {
  critical: "from-red-500 via-red-500 to-rose-600",
  high:     "from-amber-500 via-orange-500 to-amber-500",
  medium:   "from-blue-500 via-blue-400 to-indigo-500",
  low:      "from-green-500 via-emerald-500 to-green-500",
  info:     "from-gray-400 via-gray-300 to-gray-400",
};

const SEV_ICON_BG: Record<string, string> = {
  critical: "bg-red-100 text-red-600",
  high:     "bg-amber-100 text-amber-600",
  medium:   "bg-blue-100 text-blue-600",
  low:      "bg-green-100 text-green-600",
  info:     "bg-gray-100 text-gray-500",
};

function FindingDetailPanel({
  finding: f, onClose, onRefresh, canEdit,
}: {
  finding: Finding;
  onClose: () => void;
  onRefresh: () => void;
  canEdit: boolean;
}) {
  const [tab,         setTab]         = useState<DetailTab>("overview");
  const [activity,    setActivity]    = useState<ActivityEntry[]>([]);
  const [newComment,  setNewComment]  = useState("");
  const [posting,     setPosting]     = useState(false);
  const [acting,      setActing]      = useState(false);
  const [assigneeVal, setAssignee]    = useState(f.assignee ?? "");
  const [priorityVal, setPriority]    = useState(f.priority ?? 3);
  const [dueDate,     setDueDate]     = useState("");
  const [noteVal,     setNoteVal]     = useState(f.analyst_notes ?? "");
  const [copied,      setCopied]      = useState(false);

  const cveIds     = parseArr(f.cve_ids);
  const tags       = parseArr(f.tags);
  const evidence   = typeof f.evidence === "string" ? {} : (f.evidence ?? {});
  // action_plan now rendered via shared OSRemediationPanel — see Overview tab.
  const findingId  = f.external_id ?? f.display_id ?? `AL-${f.id}`;
  const cat        = catCfg(f.category);
  const score      = f.composite_score ?? f.score ?? 0;
  const stripe     = SEV_STRIPE[f.severity] ?? SEV_STRIPE.info;
  const iconBg     = SEV_ICON_BG[f.severity] ?? SEV_ICON_BG.info;

  useEffect(() => {
    fetch(`${SOC}/findings/${f.id}/activity`).then(r => r.ok ? r.json() : { activity: [] }).then(d => setActivity(d.activity ?? [])).catch(() => {});
  }, [f.id]);

  // Escape key to close.
  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", h);
    return () => document.removeEventListener("keydown", h);
  }, [onClose]);

  // Freeze background scroll while drawer is open. Safe here because the
  // drawer is portaled to document.body and won't lose its own scrollTop.
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = prev; };
  }, []);

  const act = async (newStatus: string) => {
    setActing(true);
    await patchFinding(f.id, { status: newStatus, actor: "analyst" });
    setActing(false); onRefresh();
  };

  const save = async () => {
    setActing(true);
    await patchFinding(f.id, { assignee: assigneeVal, priority: priorityVal, analyst_notes: noteVal, actor: "analyst" });
    setActing(false); onRefresh();
  };

  const postComment = async () => {
    if (!newComment.trim()) return;
    setPosting(true);
    try {
      const r = await fetch(`${SOC}/findings/${f.id}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ analyst: "analyst", comment: newComment }) });
      if (!r.ok) return;
      setNewComment("");
      fetch(`${SOC}/findings/${f.id}/activity`).then(r => r.ok ? r.json() : { activity: [] }).then(d => setActivity(d.activity ?? [])).catch(() => {});
    } catch { /* network error — posting state cleared in finally */ }
    finally { setPosting(false); }
  };

  const copyId = () => { navigator.clipboard?.writeText(findingId); setCopied(true); setTimeout(() => setCopied(false), 1400); };

  const TABS: { id: DetailTab; label: string; icon: React.ReactNode }[] = [
    { id: "overview", label: "Overview",  icon: <FileText className="w-3.5 h-3.5" /> },
    { id: "case",     label: "Case",      icon: <Shield className="w-3.5 h-3.5" /> },
    { id: "timeline", label: "Timeline",  icon: <Activity className="w-3.5 h-3.5" /> },
  ];

  const nextStatuses = STATUS_MAP[f.status]?.next ?? [];

  return createPortal(
    <>
      {/* Backdrop — portaled to body so fixed positioning is always viewport-relative */}
      <div
        className="al-backdrop-in"
        style={{ position: "fixed", top: 44, left: 0, right: 0, bottom: 0, zIndex: 40, background: "rgba(0,0,0,0.35)", backdropFilter: "blur(2px)" }}
        onClick={onClose}
        onWheel={e => e.stopPropagation()}
        onTouchMove={e => e.stopPropagation()}
      />

      {/* Sliding drawer */}
      <div
        className="al-drawer-in flex flex-col overflow-hidden"
        style={{ position: "fixed", top: 44, right: 0, bottom: 0, width: "min(520px, 100vw)", zIndex: 50, background: "#fff", boxShadow: "-4px 0 32px 0 rgba(0,0,0,0.15)" }}
      >

        {/* Severity gradient header bar */}
        <div className={cn("h-1.5 bg-gradient-to-r flex-shrink-0", stripe)} />

        {/* Drawer header */}
        <div className="flex-shrink-0 px-5 pt-4 pb-3 border-b border-gray-100 bg-white">
          {/* Top row: ID chip + badges + close */}
          <div className="flex items-center justify-between gap-3 mb-3">
            <div className="flex items-center gap-2 flex-wrap min-w-0">
              <button onClick={copyId}
                className="flex items-center gap-1 px-2 py-1 bg-orange-50 border border-orange-200 rounded-lg text-[10px] font-black text-orange-700 hover:bg-orange-100 transition-colors font-mono flex-shrink-0">
                <Hash className="w-3 h-3" />{findingId}
                {copied ? <CheckCircle2 className="w-2.5 h-2.5 text-green-500" /> : <Copy className="w-2.5 h-2.5 opacity-40" />}
              </button>
              <span className={cn("px-2.5 py-1 text-[10px] font-bold rounded-full border uppercase tracking-wide", SEV_BADGE[f.severity])}>{f.severity}</span>
              {f.kev && <span className="px-2 py-0.5 bg-red-600 text-white rounded-lg text-[9px] font-black badge-kev-pulse">KEV</span>}
              {f.exploit_available && <span className="px-2 py-0.5 bg-amber-100 text-amber-800 border border-amber-200 rounded-lg text-[9px] font-bold">EXPLOIT</span>}
            </div>
            <button onClick={onClose}
              className="w-7 h-7 flex-shrink-0 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors text-gray-400 hover:text-gray-700">
              <XCircle className="w-4 h-4" />
            </button>
          </div>

          {/* Finding title */}
          <h2 className="text-[15px] font-bold text-gray-900 leading-snug mb-2">{f.title}</h2>

          {/* Meta row: category · agent · time */}
          <div className="flex items-center gap-3 flex-wrap">
            <span className={cn("flex items-center gap-1 px-2 py-0.5 rounded-full border text-[10px] font-semibold", cat.bg, cat.color)}>
              <span className={cn("w-1.5 h-1.5 rounded-full", cat.dot)} />{cat.label}
            </span>
            {f.mitre_technique && (
              <span className="px-2 py-0.5 bg-indigo-50 text-indigo-700 border border-indigo-200 rounded-lg text-[10px] font-mono font-semibold">{f.mitre_technique}</span>
            )}
            {f.mitre_tactic && (
              <span className="px-2 py-0.5 bg-purple-50 text-purple-600 border border-purple-200 rounded-lg text-[10px] font-semibold">{f.mitre_tactic}</span>
            )}
            {tags.map(t => <span key={t} className="px-1.5 py-0.5 bg-gray-100 text-gray-500 border border-gray-200 rounded text-[9px]">{t}</span>)}
          </div>

          {/* Score strip */}
          <div className="grid grid-cols-3 gap-2.5 mt-3">
            {[
              { l: "Risk Score", v: `${score.toFixed(1)}`, sub: "/ 10",
                c: score >= 8 ? "text-red-600" : score >= 6 ? "text-amber-600" : "text-blue-600",
                bg: score >= 8 ? "bg-red-50 border-red-200" : score >= 6 ? "bg-amber-50 border-amber-200" : "bg-blue-50 border-blue-200" },
              { l: "CVSS",       v: f.cvss_score != null ? f.cvss_score.toFixed(1) : "—", sub: f.cvss_score != null ? "/ 10" : "",
                c: f.cvss_score != null && f.cvss_score >= 9 ? "text-red-600" : f.cvss_score != null && f.cvss_score >= 7 ? "text-amber-600" : "text-gray-700",
                bg: "bg-gray-50 border-gray-200" },
              { l: "EPSS", v: f.epss_score != null ? `${Math.round(f.epss_score * 100)}` : "—", sub: f.epss_score != null ? "%" : "",
                c: f.epss_score != null && f.epss_score >= 0.5 ? "text-red-600" : f.epss_score != null && f.epss_score >= 0.2 ? "text-amber-600" : "text-gray-700",
                bg: "bg-gray-50 border-gray-200" },
            ].map(s => (
              <div key={s.l} className={cn("rounded-xl border px-3 py-2.5 al-bounce-in", s.bg)}>
                <div className="flex items-baseline gap-0.5">
                  <span className={cn("text-lg font-black leading-none tabular-nums", s.c)}>{s.v}</span>
                  {s.sub && <span className="text-[10px] text-gray-400 font-medium">{s.sub}</span>}
                </div>
                <div className="text-[9px] text-gray-500 font-semibold mt-0.5 uppercase tracking-wide">{s.l}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-100 flex-shrink-0 bg-white">
          {TABS.map(t => (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={cn(
                "flex-1 flex items-center justify-center gap-1.5 py-3 text-[11px] font-bold transition-all relative",
                tab === t.id ? "text-orange-600" : "text-gray-400 hover:text-gray-600 hover:bg-gray-50"
              )}>
              {t.icon}{t.label}
              {tab === t.id && (
                <span className="absolute bottom-0 left-4 right-4 h-[2px] bg-orange-500 rounded-t-full"
                  style={{ animation: "tab-slide 0.2s ease both", transformOrigin: "left" }} />
              )}
            </button>
          ))}
        </div>

        {/* Scrollable content */}
        <div className="overflow-y-auto flex-1 bg-gray-50/30">

          {/* ── OVERVIEW ────────────────────────────────────────────────── */}
          {tab === "overview" && (
            <div className="space-y-px">

              {/* Description */}
              <div className="bg-white px-5 py-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2">Description</div>
                <p className="text-[12px] text-gray-700 leading-relaxed">{f.description}</p>
              </div>

              {/* Business impact */}
              {f.impact && (
                <div className="bg-white px-5 py-4">
                  <div className="text-[10px] font-bold text-amber-600 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5" />Business Impact
                  </div>
                  <div className="flex items-start gap-3 px-3 py-3 bg-amber-50 border border-amber-200 rounded-xl">
                    <AlertTriangle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
                    <p className="text-[11px] text-amber-900 leading-relaxed">{f.impact}</p>
                  </div>
                </div>
              )}

              {/* CVEs */}
              {cveIds.length > 0 && (
                <div className="bg-white px-5 py-4">
                  <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2.5">CVE References</div>
                  <div className="flex flex-wrap gap-1.5">
                    {cveIds.map(c => (
                      <a key={c} href={`https://nvd.nist.gov/vuln/detail/${c}`} target="_blank" rel="noopener noreferrer"
                        className="flex items-center gap-1 font-mono text-[10px] px-2.5 py-1.5 bg-blue-50 text-blue-700 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors">
                        {c}<ExternalLink className="w-3 h-3 opacity-60" />
                      </a>
                    ))}
                  </div>
                </div>
              )}

              {/* Terrain Validation — per-criterion checklist (KEV / AI / exploit / posture / …) */}
              <div className="bg-white">
                <TerrainValidationPanel f={f} />
              </div>

              {/* AI Precision validator — composite score, factor breakdown, LLM reasoning */}
              <div className="bg-white">
                <AIPrecisionPanel f={f} />
              </div>

              {/* OS-aware remediation — locked to the agent's actual OS */}
              <div className="bg-white">
                <OSRemediationPanel findingId={f.id} agentOs={f.agent_os} />
              </div>

              {/* Evidence */}
              {Object.keys(evidence).length > 0 && (
                <div className="bg-white px-5 py-4">
                  <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2">Evidence</div>
                  <pre className="text-[10px] font-mono text-emerald-300 bg-gray-950 rounded-xl p-4 overflow-auto max-h-48 whitespace-pre-wrap break-words border border-gray-800 shadow-inner leading-relaxed">
                    {JSON.stringify(evidence, null, 2)}
                  </pre>
                </div>
              )}

              {/* Detection metadata */}
              <div className="bg-white px-5 py-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3">Detection Metadata</div>
                <div className="rounded-xl border border-gray-100 overflow-hidden divide-y divide-gray-50">
                  {[
                    ["Source",     f.source ?? "—"],
                    ["Agent",      f.agent_id ?? "—"],
                    ["First seen", fmtTs(f.first_detected_at)],
                    ["Last seen",  fmtTs(f.last_detected_at)],
                    ["Scan count", String(f.scan_count)],
                  ].map(([l, v]) => (
                    <div key={l} className="flex items-center gap-4 px-3 py-2 bg-white">
                      <span className="w-20 text-[10px] text-gray-400 font-semibold flex-shrink-0">{l}</span>
                      <span className="text-[11px] text-gray-700 font-mono">{v}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* ── CASE MANAGEMENT ─────────────────────────────────────────── */}
          {tab === "case" && (
            <div className="space-y-px">

              {/* Resolved banner */}
              {["closed","false_positive","accepted_risk","duplicate"].includes(f.status) && (
                <div className={cn(
                  "mx-4 mt-4 flex items-center justify-between px-4 py-3 rounded-2xl border text-[11px] font-semibold",
                  f.status === "closed"         ? "bg-green-50 border-green-200 text-green-800" :
                  f.status === "false_positive" ? "bg-gray-100 border-gray-300 text-gray-600" :
                  f.status === "accepted_risk"  ? "bg-amber-50 border-amber-200 text-amber-800" :
                  "bg-gray-50 border-gray-200 text-gray-500"
                )}>
                  <div className="flex items-center gap-2.5">
                    {f.status === "closed"         && <CheckCircle2 className="w-4 h-4 text-green-600" />}
                    {f.status === "false_positive" && <XCircle className="w-4 h-4 text-gray-500" />}
                    {f.status === "accepted_risk"  && <Shield className="w-4 h-4 text-amber-600" />}
                    <span>
                      {f.status === "closed"         && "Finding closed"}
                      {f.status === "false_positive" && "Marked false positive"}
                      {f.status === "accepted_risk"  && "Risk accepted"}
                      {f.status === "duplicate"      && "Marked duplicate"}
                    </span>
                    {f.closed_at && <span className="opacity-60 text-[10px]">· {relTime(f.closed_at)}</span>}
                  </div>
                  {canEdit && (
                    <button onClick={() => act("triaging")} disabled={acting}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-blue-200 text-blue-700 rounded-xl text-[10px] font-bold hover:bg-blue-50 transition-colors disabled:opacity-50">
                      <RotateCcw className="w-3 h-3" />Reopen
                    </button>
                  )}
                </div>
              )}

              {/* Workflow strip */}
              <div className="bg-white px-5 py-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3">Case Workflow</div>
                <div className="overflow-x-auto pb-1">
                  <WorkflowStrip current={f.status} />
                </div>
              </div>

              {/* Transitions */}
              <div className="bg-white px-5 py-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
                  <GitBranch className="w-3.5 h-3.5 text-orange-500" />Move To
                </div>
                {nextStatuses.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {nextStatuses.map(ns => {
                      const sc = STATUS_MAP[ns];
                      if (!sc) return null;
                      const isClose = ["closed","false_positive","accepted_risk","duplicate"].includes(ns);
                      return (
                        <button key={ns} onClick={() => act(ns)} disabled={acting || !canEdit}
                          className={cn(
                            "flex items-center gap-1.5 px-3.5 py-2 rounded-xl border text-[11px] font-bold transition-all hover:shadow-sm disabled:opacity-50",
                            sc.badge
                          )}>
                          {ns === "closed"        && <CheckCircle2 className="w-3.5 h-3.5" />}
                          {ns === "false_positive" && <XCircle className="w-3.5 h-3.5" />}
                          {ns === "new"            && <RotateCcw className="w-3.5 h-3.5" />}
                          {ns === "triaging"       && <AlertTriangle className="w-3.5 h-3.5" />}
                          {ns === "investigating"  && <Search className="w-3.5 h-3.5" />}
                          {ns === "in_remediation" && <Shield className="w-3.5 h-3.5" />}
                          {ns === "accepted_risk"  && <Shield className="w-3.5 h-3.5" />}
                          {ns === "duplicate"      && <Layers className="w-3.5 h-3.5" />}
                          {sc.label}
                          {isClose && <span className="text-[9px] opacity-50">→ close</span>}
                        </button>
                      );
                    })}
                  </div>
                ) : (
                  <p className="text-[11px] text-gray-400">No further transitions available.</p>
                )}
              </div>

              {/* Assignment + Priority + Notes */}
              <div className="bg-white px-5 py-4 space-y-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest flex items-center gap-1.5">
                  <User className="w-3.5 h-3.5 text-orange-500" />Assignment
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-[10px] text-gray-500 font-semibold block mb-1.5">Assignee</label>
                    <input type="text" placeholder="analyst@company.com" value={assigneeVal} onChange={e => setAssignee(e.target.value)}
                      className="w-full px-3 py-2 text-[12px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 transition-all" />
                  </div>
                  <div>
                    <label className="text-[10px] text-gray-500 font-semibold block mb-1.5">Priority</label>
                    <select value={priorityVal} onChange={e => setPriority(Number(e.target.value))}
                      className="w-full px-3 py-2 text-[12px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 cursor-pointer">
                      {Object.entries(PRIORITIES).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
                    </select>
                  </div>
                </div>
                <div>
                  <label className="text-[10px] text-gray-500 font-semibold block mb-1.5 flex items-center gap-1"><Calendar className="w-3.5 h-3.5" />Due Date</label>
                  <input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)}
                    className="w-full px-3 py-2 text-[12px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 transition-all" />
                </div>
                <div>
                  <label className="text-[10px] text-gray-500 font-semibold block mb-1.5 flex items-center gap-1"><FileText className="w-3.5 h-3.5" />Analyst Notes</label>
                  <textarea rows={4} value={noteVal} onChange={e => setNoteVal(e.target.value)}
                    placeholder="Investigation notes, context, justification…"
                    className="w-full px-3 py-2 text-[12px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 resize-none transition-all leading-relaxed" />
                </div>
                {canEdit && (
                  <button onClick={save} disabled={acting}
                    className="flex items-center gap-2 px-5 py-2.5 bg-orange-500 hover:bg-orange-600 text-white text-[11px] font-bold rounded-xl transition-all shadow-sm hover:shadow-md w-full justify-center disabled:opacity-60">
                    <CheckCircle2 className="w-4 h-4" />Save Case Updates
                    {acting && <span className="text-[10px] opacity-70">Saving…</span>}
                  </button>
                )}
              </div>

              {/* SLA */}
              {f.sla_status && (
                <div className="bg-white px-5 py-4">
                  <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2.5 flex items-center gap-1.5">
                    <Clock className="w-3.5 h-3.5" />SLA Status
                  </div>
                  <div className={cn("flex items-center gap-3 px-4 py-3 rounded-xl border text-[11px] font-semibold",
                    f.sla_status === "breached" ? "bg-red-50 border-red-200 text-red-700" :
                    f.sla_status === "warning"  ? "bg-amber-50 border-amber-200 text-amber-700" :
                    "bg-green-50 border-green-200 text-green-700")}>
                    <Clock className={cn("w-4 h-4 flex-shrink-0", f.sla_status === "breached" && "al-heartbeat")} />
                    SLA {f.sla_status.toUpperCase()}
                    {f.sla_due && <span className="ml-auto text-[10px] opacity-70">Due {fmtTs(f.sla_due)}</span>}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── TIMELINE ────────────────────────────────────────────────── */}
          {tab === "timeline" && (
            <div className="space-y-px">
              <div className="bg-white px-5 py-4">
                <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-1.5">
                  <Activity className="w-3.5 h-3.5 text-orange-500" />Activity Log
                </div>
                {activity.length === 0 ? (
                  <div className="py-12 text-center">
                    <Activity className="w-8 h-8 text-gray-200 mx-auto mb-2" />
                    <p className="text-[11px] text-gray-400">No activity recorded yet</p>
                  </div>
                ) : (
                  <div className="relative space-y-4">
                    <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-100" />
                    {activity.map((a, i) => (
                      <div key={i} className="flex items-start gap-4 al-row-in" style={{ animationDelay: `${i * 40}ms` }}>
                        <div className="w-8 h-8 rounded-full bg-orange-50 border-2 border-white ring-1 ring-gray-100 flex items-center justify-center flex-shrink-0 z-10 shadow-sm">
                          <span className="text-[10px] font-black text-orange-600">{(a.actor?.[0] ?? "?").toUpperCase()}</span>
                        </div>
                        <div className="flex-1 min-w-0 pb-1">
                          <div className="flex items-center gap-2 flex-wrap mb-0.5">
                            <span className="text-[11px] font-bold text-gray-800">{a.actor}</span>
                            <span className="text-[11px] text-gray-500">{a.action.replace(/_/g, " ")}</span>
                            {a.old_value && a.new_value && (
                              <span className="text-[10px] text-gray-400 font-mono bg-gray-50 px-1.5 py-0.5 rounded border border-gray-100">
                                {a.old_value} → {a.new_value}
                              </span>
                            )}
                            <span className="ml-auto text-[10px] text-gray-400 flex-shrink-0">{relTime(a.created_at)}</span>
                          </div>
                          {a.comment && (
                            <p className="text-[11px] text-gray-600 mt-1 bg-gray-50 rounded-xl px-3 py-2 border border-gray-100 leading-relaxed">{a.comment}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Add comment */}
              {canEdit && (
                <div className="bg-white px-5 py-4">
                  <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
                    <MessageSquare className="w-3.5 h-3.5 text-blue-500" />Add Investigation Note
                  </div>
                  <div className="space-y-2.5">
                    <textarea rows={3} value={newComment} onChange={e => setNewComment(e.target.value)}
                      onKeyDown={e => { if (e.key === "Enter" && e.ctrlKey) postComment(); }}
                      placeholder="Add investigation note… (Ctrl+Enter to post)"
                      className="w-full px-3 py-2.5 text-[12px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 resize-none transition-all leading-relaxed" />
                    <button onClick={postComment} disabled={posting || !newComment.trim()}
                      className="flex items-center gap-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white text-[11px] font-bold rounded-xl transition-all disabled:opacity-50">
                      <Send className="w-3.5 h-3.5" />{posting ? "Posting…" : "Post Note"}
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </>,
    document.body
  );
}

// ── Main Findings Page ────────────────────────────────────────────────────────

export default function ThreatQueue() {
  const { can } = useRBAC();
  const { range } = useTimeRange();
  const { refreshRevision, registerRefreshRequest } = useRefresh();
  const qs = rangeToParams(range).toString();

  // Data
  const [findings, setFindings]   = useState<Finding[]>([]);
  const [loading,  setLoading]    = useState(true);
  const [error,    setError]      = useState<string | null>(null);
  const [lastSync, setLastSync]   = useState(0);

  // Configured thresholds from /api/v1/settings/validation (echoed by the
  // findings endpoint when validated_only=true so the UI doesn't need a
  // separate round-trip).
  const [globalThreshold,      setGlobalThreshold]      = useState<number | null>(null);
  const [effectiveThresholds,  setEffectiveThresholds]  = useState<{
    global?:  number;
    terrain?: Record<string, number>;
    agent?:   Record<string, number>;
  } | null>(null);
  const [filterStats, setFilterStats] = useState<{
    active_total?:    number;
    validated_count?: number;
    below_threshold?: number;
    highest_score?:   number | null;
    top_scores?: Array<{ id: number; title: string; agent_id: string; category: string; precision_score: number }>;
    by_terrain?: Record<string, { validated: number; below: number }>;
  } | null>(null);
  const [rescoring, setRescoring] = useState(false);
  const [rescoreReport, setRescoreReport] = useState<{
    scanned: number; updated: number;
    histogram: Record<string, number>;
  } | null>(null);

  // Selection
  const [selected, setSelected]   = useState<Set<number>>(new Set());
  const [bulkActing, setBulkActing] = useState(false);

  // Expanded detail
  const [detailId, setDetailId]   = useState<number | null>(null);

  // View mode — controls active_only / view param
  const [viewMode, setViewMode]   = useState<ValidatedView>("active");

  // Filters
  const [catTab,   setCatTab]     = useState("all");
  const [severity, setSeverity]   = useState("");
  const [status,   setStatus]     = useState("");
  const [agentId,  setAgentId]    = useState("");
  const [slaOnly,  setSlaOnly]    = useState(false);
  const [kevOnly,  setKevOnly]    = useState(false);
  const [search,   setSearch]     = useState("");
  const [rawSearch,setRawSearch]  = useState("");
  const [adv,      setAdv]        = useState<FilterCondition[]>([]);
  const [sortKey,  setSortKey]    = useState("composite_score");
  const [sortAsc,  setSortAsc]    = useState(false);
  const debRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Pagination
  const PAGE_SIZE = 50;
  const [page, setPage] = useState(0);

  // Reset to first page whenever any filter / sort / view changes
  useEffect(() => { setPage(0); }, [catTab, severity, status, agentId, slaOnly, kevOnly, search, sortKey, sortAsc, viewMode, adv]);


  const load = useCallback(async () => {
    const settleRefresh = registerRefreshRequest(refreshRevision);
    let requestError: unknown;
    const p = validatedFindingsQuery(viewMode);
    p.set("limit", "500");
    p.set("sort_by", sortKey);
    if (severity) p.set("severity", severity);
    if (agentId)  p.set("agent_id", agentId);
    // Don't send status param when view=closed (backend handles terminal states)
    if (status && viewMode !== "closed") p.set("status", status);
    if (slaOnly)  p.set("sla_breached", "true");
    if (search)   p.set("search",   search);
    // Validated Findings is always the validated projection. Historical
    // review remains available by selecting a closed/all view within it.
    // Append global time window (first_detected_at filter).
    for (const [k, v] of new URLSearchParams(qs)) p.set(k, v);
    try {
      const r = await fetch(`${VALIDATED_FINDINGS_URL}?${p}`);
      if (!r.ok) throw new Error(`${r.status}`);
      const d = await r.json();
      setFindings(d.findings ?? []);
      setEffectiveThresholds(d.effective_thresholds ?? null);
      setGlobalThreshold(typeof d.global_threshold === "number" ? d.global_threshold : null);
      setFilterStats(d.validation_filter_stats ?? null);
      setError(null);
    } catch (caught) {
      requestError = caught;
      setError(String(caught));
    } finally {
      setLoading(false);
      setLastSync(Math.floor(Date.now() / 1000));
      settleRefresh(requestError);
    }
  }, [severity, status, agentId, slaOnly, search, sortKey, viewMode, qs, refreshRevision, registerRefreshRequest]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (range.kind === "absolute") return;
    const timer = window.setInterval(() => void load(), 30_000);
    return () => window.clearInterval(timer);
  }, [load, range.kind]);

  const handleSearch = (v: string) => {
    setRawSearch(v);
    if (debRef.current) clearTimeout(debRef.current);
    debRef.current = setTimeout(() => setSearch(v), 300);
  };

  // Category filter
  const baseFiltered = findings.filter(f => {
    if (catTab !== "all") {
      const k = catKey(f.category);
      const grouped: Record<string, string[]> = {
        persist: ["persist","execution","malware","script","process","container","service","task","lateral","covert"],
        reach:   ["reach","network","connection","c2","port","arp","dns","tunnel"],
        surface: ["surface","package","vulnerability","cve","sbom","config","binary","sysctl","app"],
        user:    ["user","identity","account","credential"],
        security:["security","posture","sip","firewall"],
      };
      const allowed = grouped[catTab] ?? [catTab];
      if (!allowed.includes(k) && !f.category.toLowerCase().includes(catTab)) return false;
    }
    if (kevOnly && !f.kev) return false;
    return true;
  });

  // Advanced field+operator conditions (ANDed on top of the quick filters)
  const filtered = applyAdvancedConditions(baseFiltered, adv);

  // Sort
  const sorted = [...filtered].sort((a, b) => {
    let d = 0;
    if (sortKey === "composite_score") d = (b.composite_score ?? b.score) - (a.composite_score ?? a.score);
    else if (sortKey === "first_detected_at") d = b.first_detected_at - a.first_detected_at;
    else if (sortKey === "severity") {
      const o: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
      d = (o[b.severity] ?? 0) - (o[a.severity] ?? 0);
    }
    return sortAsc ? -d : d;
  });

  const toggleSort = (key: string) => { sortKey === key ? setSortAsc(a => !a) : (setSortKey(key), setSortAsc(false)); };

  // Pagination slice
  const totalPages = Math.max(1, Math.ceil(sorted.length / PAGE_SIZE));
  const pageItems  = sorted.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const pageStart  = page * PAGE_SIZE + 1;
  const pageEnd    = Math.min((page + 1) * PAGE_SIZE, sorted.length);

  // Selection
  const toggleOne  = (id: number) => setSelected(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });
  const toggleAll  = () => setSelected(prev => prev.size === sorted.length ? new Set() : new Set(sorted.map(f => f.id)));
  const clearSel   = () => setSelected(new Set());

  const doBulk = async (action: string, value?: string) => {
    if (!can("bulk_action") || selected.size === 0) return;
    setBulkActing(true);
    await bulkAction(Array.from(selected), action, value);
    clearSel();
    await load();
    setBulkActing(false);
  };

  // ── Inline quick actions (per-row buttons) ───────────────────────────────
  const [quickActing, setQuickActing] = useState<number | null>(null); // finding id being acted on

  const quickAct = async (findingId: number, endpoint: string) => {
    setQuickActing(findingId);
    try {
      await fetch(`${SOC}/findings/${findingId}/${endpoint}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ actor: "analyst" }),
      });
      // Optimistic: close the detail panel if it was open for this finding
      if (detailId === findingId) setDetailId(null);
      await load();
    } finally {
      setQuickActing(null);
    }
  };

  // Stats
  const total      = findings.length;
  const critical   = findings.filter(f => f.severity === "critical").length;
  const high       = findings.filter(f => f.severity === "high").length;
  const isNew      = findings.filter(f => f.status === "new").length;
  const slaBreached= findings.filter(f => f.sla_status === "breached").length;
  const unassigned = findings.filter(f => !f.assignee && !["closed","false_positive","accepted_risk"].includes(f.status)).length;
  const kevCount   = findings.filter(f => f.kev).length;

  const detailFinding  = sorted.find(f => f.id === detailId) ?? null;
  const closeDetail    = useCallback(() => setDetailId(null), []);

  // Sortable header
  const SortTh = ({ label, k }: { label: string; k: string }) => (
    <th onClick={() => toggleSort(k)} className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider cursor-pointer hover:text-gray-600 select-none whitespace-nowrap">
      <span className="flex items-center gap-1">{label}
        {sortKey === k && <span className="text-orange-500">{sortAsc ? "↑" : "↓"}</span>}
      </span>
    </th>
  );

  return (
    <div className="space-y-4 pb-6">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="h-1 bg-gradient-to-r from-orange-400 via-amber-400 to-orange-500 relative overflow-hidden">
          <div className="absolute inset-0 al-scan" style={{ background: "linear-gradient(90deg,transparent,rgba(255,255,255,0.5),transparent)", width: "40%" }} />
        </div>
        <div className="p-5">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 rounded-xl bg-orange-50 border border-orange-100 flex items-center justify-center flex-shrink-0">
                <AlertTriangle className="w-5 h-5 text-orange-500" />
              </div>
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <h1 className="text-base font-bold text-gray-900">Validated Findings</h1>
                  <span className="px-2 py-0.5 bg-orange-50 text-orange-700 border border-orange-200 rounded-full text-[9px] font-black">LIVE</span>
                  {globalThreshold != null && (
                    <span
                      className="px-2 py-0.5 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full text-[9px] font-black uppercase tracking-wide"
                      title="Configured Detection Confidence threshold from Settings → Validation. Per-terrain and per-agent overrides apply on top of this."
                    >
                      Detection Confidence ≥ {Math.round(globalThreshold * 100)}%
                    </span>
                  )}
                  {effectiveThresholds?.terrain && Object.keys(effectiveThresholds.terrain).length > 0 && (
                    <span className="px-2 py-0.5 bg-purple-50 text-purple-700 border border-purple-200 rounded-full text-[9px] font-bold uppercase tracking-wide"
                          title={"Per-terrain overrides:\n" + Object.entries(effectiveThresholds.terrain).map(([k,v]) => `  ${k}: ${Math.round(v*100)}%`).join("\n")}>
                      {Object.keys(effectiveThresholds.terrain).length} terrain override{Object.keys(effectiveThresholds.terrain).length > 1 ? "s" : ""}
                    </span>
                  )}
                  {effectiveThresholds?.agent && Object.keys(effectiveThresholds.agent).length > 0 && (
                    <span className="px-2 py-0.5 bg-indigo-50 text-indigo-700 border border-indigo-200 rounded-full text-[9px] font-bold uppercase tracking-wide"
                          title={"Per-agent overrides:\n" + Object.entries(effectiveThresholds.agent).map(([k,v]) => `  ${k}: ${Math.round(v*100)}%`).join("\n")}>
                      {Object.keys(effectiveThresholds.agent).length} agent override{Object.keys(effectiveThresholds.agent).length > 1 ? "s" : ""}
                    </span>
                  )}
                </div>
                <p className="text-xs text-gray-500 mt-0.5">
                  Filtered per attack terrain · Detection Confidence threshold resolved from <a href="#" onClick={e => { e.preventDefault(); window.location.hash = "#settings"; }} className="text-purple-600 hover:underline">Settings → Validation</a> · auto-refresh 30s
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 border border-gray-200 rounded-xl text-[9px] text-gray-500 font-medium">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 al-heartbeat" />
                {lastSync ? `Synced ${relTime(lastSync)}` : "Loading…"}
              </div>
              <button onClick={load} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-gray-100 hover:bg-orange-50 hover:border-orange-200 border border-gray-200 text-gray-600 hover:text-orange-600 text-xs font-semibold transition-all">
                <RefreshCw className={cn("w-3.5 h-3.5", loading && "animate-spin")} />
              </button>
            </div>
          </div>

          {/* KPI strip */}
          <div className="grid grid-cols-7 gap-2 mt-4 pt-4 border-t border-gray-100">
            <KpiTile label="Total"       value={total}       color="text-gray-800"   bg="bg-gray-50 border-gray-200"     icon={<AlertCircle className="w-3 h-3" />}     delay={0}   />
            <KpiTile label="Critical"    value={critical}    color="text-red-700"    bg="bg-red-50 border-red-200"       icon={<AlertTriangle className="w-3 h-3" />}   delay={40}  />
            <KpiTile label="High"        value={high}        color="text-amber-700"  bg="bg-amber-50 border-amber-200"   icon={<Zap className="w-3 h-3" />}             delay={80}  />
            <KpiTile label="New"         value={isNew}       color={isNew > 0 ? "text-red-600" : "text-green-600"} bg={isNew > 0 ? "bg-red-50 border-red-200" : "bg-green-50 border-green-200"} icon={<Radio className="w-3 h-3" />} delay={120} />
            <KpiTile label="SLA Breach"  value={slaBreached} color={slaBreached > 0 ? "text-red-600" : "text-green-600"} bg={slaBreached > 0 ? "bg-red-50 border-red-200" : "bg-green-50 border-green-200"} icon={<Clock className="w-3 h-3" />} delay={160} />
            <KpiTile label="Unassigned"  value={unassigned}  color={unassigned > 0 ? "text-amber-700" : "text-green-600"} bg={unassigned > 0 ? "bg-amber-50 border-amber-200" : "bg-green-50 border-green-200"} icon={<User className="w-3 h-3" />} delay={200} />
            <KpiTile label="KEV Listed"  value={kevCount}    color={kevCount > 0 ? "text-red-700" : "text-gray-500"}    bg={kevCount > 0 ? "bg-red-50 border-red-200" : "bg-gray-50 border-gray-200"}   icon={<Zap className="w-3 h-3" />} delay={240} />
          </div>

          {/* ── Per-terrain breakdown — which terrains are clearing the threshold ── */}
          {viewMode === "active" && filterStats?.by_terrain && (
            <div className="mt-4 pt-3 border-t border-gray-100">
              <div className="flex items-center justify-between mb-2">
                <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest flex items-center gap-1.5">
                  <Layers className="w-3 h-3 text-purple-500" />
                  Filtered by Attack Terrain
                </div>
                <div className="text-[9px] text-gray-400">
                  validated / active per terrain
                </div>
              </div>
              <div className="grid grid-cols-5 gap-2">
                {([
                  { id: "citadels", label: "Citadels", desc: "Execution & persistence",  color: "red" },
                  { id: "vector",   label: "Vector",   desc: "Network & reachability",   color: "blue" },
                  { id: "origin",   label: "Origin",   desc: "Surface, packages, CVEs",  color: "amber" },
                  { id: "identity", label: "Identity", desc: "Accounts & credentials",   color: "indigo" },
                  { id: "posture",  label: "Posture",  desc: "Security controls",        color: "emerald" },
                ] as { id: string; label: string; desc: string; color: string }[]).map(t => {
                  const c     = filterStats.by_terrain?.[t.id] ?? { validated: 0, below: 0 };
                  const total = c.validated + c.below;
                  const pct   = total > 0 ? Math.round((c.validated / total) * 100) : 0;
                  const colors: Record<string, { tint: string; text: string; bar: string }> = {
                    red:     { tint: "bg-red-50 border-red-200",       text: "text-red-700",     bar: "bg-red-500" },
                    blue:    { tint: "bg-blue-50 border-blue-200",     text: "text-blue-700",    bar: "bg-blue-500" },
                    amber:   { tint: "bg-amber-50 border-amber-200",   text: "text-amber-700",   bar: "bg-amber-500" },
                    indigo:  { tint: "bg-indigo-50 border-indigo-200", text: "text-indigo-700",  bar: "bg-indigo-500" },
                    emerald: { tint: "bg-emerald-50 border-emerald-200", text: "text-emerald-700", bar: "bg-emerald-500" },
                  };
                  const C = colors[t.color];
                  return (
                    <div key={t.id} className={cn("rounded-xl border p-2.5", C.tint)}>
                      <div className="flex items-baseline justify-between gap-1">
                        <span className={cn("text-[10px] font-bold uppercase tracking-wide", C.text)}>{t.label}</span>
                        <span className="text-[9px] tabular-nums text-gray-600">
                          <strong>{c.validated}</strong>
                          <span className="opacity-50"> / {total}</span>
                        </span>
                      </div>
                      <div className="text-[8px] text-gray-500 mb-1.5 truncate">{t.desc}</div>
                      <div className="h-1 bg-white rounded-full overflow-hidden">
                        <div className={cn("h-full transition-all", C.bar)} style={{ width: `${pct}%` }} />
                      </div>
                      <div className="text-[8px] mt-1 text-gray-400 font-mono">
                        {total === 0 ? "none active" : `${pct}% pass`}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      {error && (
        <div className="px-4 py-3 bg-red-50 border border-red-200 rounded-2xl text-xs text-red-700 flex items-center gap-2 al-row-in">
          <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />{error}
        </div>
      )}

      {/* ── Threshold-aware "why are my findings missing" banner ─────────────────
          Shown when validated_only is in effect AND there are active findings
          that exist but fall below the configured threshold.  Lets the user
          either drop the threshold or trigger a retro-rescore in one click. */}
      {viewMode === "active" && filterStats
        && (filterStats.active_total ?? 0) > 0
        && (filterStats.below_threshold ?? 0) > 0
        && (
        <div className="px-4 py-3 bg-amber-50 border border-amber-200 rounded-2xl text-[11px] al-row-in">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1 min-w-0">
              <div className="font-bold text-amber-900">
                {filterStats.below_threshold} active finding{(filterStats.below_threshold ?? 0) > 1 ? "s" : ""} below your {Math.round((globalThreshold ?? 0.9) * 100)}% threshold
              </div>
              <div className="text-[10px] text-amber-800 mt-0.5">
                {filterStats.validated_count ?? 0} of {filterStats.active_total ?? 0} active findings meet the configured Validated bar.
                {filterStats.highest_score != null && (
                  <> Highest score: <strong>{Math.round(filterStats.highest_score * 100)}%</strong>.</>
                )}
              </div>
              {!!filterStats.top_scores?.length && (
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {filterStats.top_scores.map(s => (
                    <span key={s.id}
                          className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-white border border-amber-200 text-amber-800">
                      {Math.round(s.precision_score * 100)}% · {s.title.slice(0, 32)}
                    </span>
                  ))}
                </div>
              )}
              <div className="mt-2 flex items-center gap-2 flex-wrap">
                <button
                  disabled={rescoring}
                  onClick={async () => {
                    setRescoring(true); setRescoreReport(null);
                    try {
                      await runValidationRecompute(fetch, setRescoreReport);
                      await load();
                    } finally { setRescoring(false); }
                  }}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-amber-600 hover:bg-amber-700 disabled:bg-amber-300 text-white text-[10px] font-bold rounded-lg transition-colors">
                  <RefreshCw className={cn("w-3 h-3", rescoring && "animate-spin")} />
                  {rescoring ? "Rescoring…" : "Rescore all findings"}
                </button>
                <span className="text-[9px] text-amber-700">
                  Older findings may pre-date the validator. Rescoring recomputes them against the current criteria.
                </span>
              </div>
              {rescoreReport && (
                <div className="mt-2 px-2 py-1.5 rounded bg-white border border-emerald-200 text-[10px] text-emerald-800">
                  <strong>Rescored {rescoreReport.updated} of {rescoreReport.scanned} findings.</strong>{" "}
                  Score distribution:&nbsp;
                  {Object.entries(rescoreReport.histogram).map(([band, n]) => (
                    <span key={band} className="ml-1.5 inline-block font-mono">
                      {band}%: <strong>{n}</strong>
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ── View mode toggle ─────────────────────────────────────────────────── */}
      <div className="flex items-center gap-2">
        {([
          { id: "active", label: "Active",   desc: "Open findings",          color: "bg-orange-500 text-white", badge: findings.length },
          { id: "closed", label: "Resolved", desc: "Closed / FP / Accepted", color: "bg-green-600 text-white",  badge: null },
          { id: "all",    label: "All",       desc: "Every finding",          color: "bg-gray-700 text-white",   badge: null },
        ] as { id: "active"|"closed"|"all"; label: string; desc: string; color: string; badge: number|null }[]).map(v => (
          <button
            key={v.id}
            onClick={() => { setViewMode(v.id); setStatus(""); }}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-xl border text-[11px] font-bold transition-all",
              viewMode === v.id
                ? `${v.color} border-transparent shadow-sm`
                : "bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50"
            )}
          >
            {v.label}
            {v.id === "active" && (
              <span className={cn("px-1.5 py-0.5 rounded-full text-[9px] font-black",
                viewMode === "active" ? "bg-white/25 text-white" : "bg-gray-100 text-gray-500")}>
                {findings.length}
              </span>
            )}
            <span className={cn("text-[9px] hidden sm:inline", viewMode === v.id ? "opacity-70" : "text-gray-400")}>
              {v.desc}
            </span>
          </button>
        ))}
      </div>

      {/* ── Category tabs ────────────────────────────────────────────────────── */}
      <div className="flex items-center gap-1 bg-white border border-gray-200 rounded-2xl p-1.5 shadow-sm overflow-x-auto">
        {CAT_GROUPS.map(g => {
          const count = g.key === "all" ? findings.length : findings.filter(f => {
            const k = catKey(f.category);
            const grouped: Record<string, string[]> = {
              persist: ["persist","execution","malware","process","script","container","service","task","lateral","covert"],
              reach:   ["reach","network","connection","c2","port","arp","dns","tunnel"],
              surface: ["surface","package","vulnerability","sbom","config","binary","sysctl","app"],
              user:    ["user","identity","account","credential"],
              security:["security","posture","sip","firewall"],
            };
            return (grouped[g.key] ?? [g.key]).includes(k) || f.category.toLowerCase().includes(g.key);
          }).length;
          return (
            <button key={g.key} onClick={() => setCatTab(g.key)}
              className={cn("flex items-center gap-1.5 py-1.5 px-3 rounded-xl text-[11px] font-bold whitespace-nowrap transition-all flex-shrink-0",
                catTab === g.key ? "bg-orange-500 text-white shadow-sm" : "text-gray-500 hover:bg-gray-50 hover:text-gray-700")}>
              {g.label}
              <span className={cn("px-1.5 py-0.5 rounded-full text-[8px] font-black", catTab === g.key ? "bg-white/20 text-white" : "bg-gray-100 text-gray-500")}>
                {count}
              </span>
            </button>
          );
        })}
      </div>

      {/* ── Table card ─────────────────────────────────────────────────────────── */}
      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <div className="h-0.5 bg-gradient-to-r from-orange-400 via-amber-400 to-orange-500" />

          {/* Filter bar + bulk actions */}
          <div className="flex items-center gap-2 px-5 py-3 border-b border-gray-100 bg-gray-50/60 flex-wrap">
            <Filter className="w-3.5 h-3.5 text-gray-400 flex-shrink-0" />
            <div className="relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-400 pointer-events-none" />
              <input value={rawSearch} onChange={e => handleSearch(e.target.value)} placeholder="Search findings…"
                className="pl-7 pr-3 py-1.5 text-[11px] border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-orange-200 w-44 transition-all" />
            </div>
            <select value={severity} onChange={e => setSeverity(e.target.value)}
              className="px-2 py-1.5 text-[10px] border border-gray-200 rounded-xl bg-white text-gray-700 focus:outline-none cursor-pointer">
              <option value="">All Severity</option>
              {["critical","high","medium","low"].map(s => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}
            </select>
            <AgentSelect value={agentId} onChange={setAgentId} compact />
            <select value={status} onChange={e => setStatus(e.target.value)}
              className="px-2 py-1.5 text-[10px] border border-gray-200 rounded-xl bg-white text-gray-700 focus:outline-none cursor-pointer">
              <option value="">All Status</option>
              {STATUS_FLOW.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}
            </select>
            <label className="flex items-center gap-1 cursor-pointer text-[10px] text-gray-600 font-medium">
              <input type="checkbox" checked={slaOnly} onChange={e => setSlaOnly(e.target.checked)} className="rounded accent-orange-500" />
              SLA Breached
            </label>
            <label className="flex items-center gap-1 cursor-pointer text-[10px] text-gray-600 font-medium">
              <input type="checkbox" checked={kevOnly} onChange={e => setKevOnly(e.target.checked)} className="rounded accent-red-500" />
              KEV Only
            </label>

            {/* Advanced field+operator filter */}
            <AdvancedFilter conditions={adv} setConditions={setAdv} />

            {/* Bulk action strip */}
            {selected.size > 0 && can("bulk_action") && (
              <div className="ml-auto flex items-center gap-1.5 pl-3 border-l border-gray-200 flex-shrink-0 flex-wrap">
                <span className="px-2.5 py-1 bg-orange-500 text-white text-[10px] font-black rounded-xl al-heartbeat">
                  {selected.size} selected
                </span>
                {[
                  { label: "Triage",       action: "triaging",       cls: "bg-amber-50 text-amber-700 border-amber-200",  icon: <AlertTriangle className="w-3 h-3" /> },
                  { label: "Investigate",  action: "investigating",  cls: "bg-blue-50 text-blue-700 border-blue-200",     icon: <ChevronRight className="w-3 h-3" /> },
                  { label: "Close",        action: "closed",         cls: "bg-green-50 text-green-700 border-green-200",  icon: <CheckCircle2 className="w-3 h-3" /> },
                  { label: "Accept Risk",  action: "accepted_risk",  cls: "bg-amber-50 text-amber-600 border-amber-200",  icon: <Shield className="w-3 h-3" /> },
                  { label: "False Pos.",   action: "false_positive", cls: "bg-gray-100 text-gray-500 border-gray-300",    icon: <XCircle className="w-3 h-3" /> },
                ].map(b => (
                  <button key={b.action} onClick={() => doBulk("status", b.action)} disabled={bulkActing}
                    className={cn("flex items-center gap-1 px-2.5 py-1.5 rounded-xl border text-[10px] font-bold transition-all hover:shadow-sm disabled:opacity-50", b.cls)}>
                    {b.icon}{b.label}
                  </button>
                ))}
                <button onClick={clearSel} className="p-1.5 rounded-xl hover:bg-gray-100 text-gray-400 hover:text-gray-600">
                  <XCircle className="w-3.5 h-3.5" />
                </button>
              </div>
            )}

            {selected.size === 0 && (
              <div className="ml-auto text-[10px] text-gray-400 flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 al-heartbeat" />
                {sorted.length} of {total} findings
              </div>
            )}
          </div>

          {/* Table */}
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-gray-50/80 border-b border-gray-100">
                  <th className="pl-4 pr-2 py-2.5 w-10">
                    <button onClick={toggleAll} className="flex items-center">
                      {selected.size > 0 && selected.size === sorted.length
                        ? <CheckSquare className="w-3.5 h-3.5 text-orange-500" />
                        : selected.size > 0
                        ? <CheckSquare className="w-3.5 h-3.5 text-orange-300" />
                        : <Square className="w-3.5 h-3.5 text-gray-300 hover:text-gray-500" />}
                    </button>
                  </th>
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider whitespace-nowrap">ID</th>
                  <SortTh label="Finding" k="title" />
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider">Category</th>
                  <SortTh label="Score" k="composite_score" />
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider">Status</th>
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider">SLA</th>
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider">Assignee</th>
                  <th className="px-3 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider">Agent</th>
                  <SortTh label="Detected" k="first_detected_at" />
                  <th className="px-2 py-2.5 text-left text-[9px] font-black text-gray-400 uppercase tracking-wider whitespace-nowrap w-[120px]">Actions</th>
                  <th className="pr-3 py-2.5 w-6" />
                </tr>
              </thead>
              <tbody>
                {loading && findings.length === 0 ? (
                  Array.from({ length: 6 }).map((_, i) => (
                    <tr key={i} className="border-b border-gray-50">
                      {Array.from({ length: 11 }).map((_, j) => (
                        <td key={j} className="px-3 py-3"><div className="h-3 bg-gray-100 rounded-full animate-pulse" style={{ width: j === 2 ? "70%" : "40%", animationDelay: `${i*80+j*30}ms` }} /></td>
                      ))}
                    </tr>
                  ))
                ) : sorted.length === 0 ? (
                  <tr><td colSpan={11} className="py-20 text-center">
                    <AlertCircle className="w-10 h-10 text-gray-200 mx-auto mb-3" />
                    <p className="text-[11px] text-gray-400 font-medium">No findings match the current filters</p>
                  </td></tr>
                ) : (
                  pageItems.map((f, idx) => {
                    const isChecked = selected.has(f.id);
                    const isDetail  = detailId === f.id;
                    const isCrit    = f.severity === "critical";
                    const isSlaBreached = f.sla_status === "breached";
                    const cat       = catCfg(f.category);
                    const sc        = STATUS_MAP[f.status];
                    const score     = f.composite_score ?? f.score;
                    const fid       = f.external_id ?? f.display_id ?? `AL-${String(f.id).padStart(5, "0")}`;

                    return (
                      <tr key={f.id}
                        className={cn(
                          "border-b border-gray-100/80 transition-all al-row-in group",
                          isDetail  ? "bg-orange-50/60 shadow-[inset_3px_0_0_#f97316]" :
                          isChecked ? "bg-orange-50/40 shadow-[inset_3px_0_0_#fb923c]" :
                          isSlaBreached ? "bg-red-50/20 hover:bg-red-50/40 shadow-[inset_3px_0_0_#ef4444]" :
                          isCrit ? cn("al-glow-critical hover:bg-red-50/20 shadow-[inset_3px_0_0_#ef4444]") :
                          f.severity === "high" ? "hover:bg-amber-50/20 shadow-[inset_3px_0_0_#f59e0b]" :
                          "hover:bg-gray-50/80",
                          isCrit && "al-glow-critical",
                        )}
                        style={{ animationDelay: `${Math.min(idx * 25, 400)}ms` }}
                      >
                        {/* Checkbox */}
                        <td className="pl-4 pr-2 py-3 w-10">
                          <button onClick={() => toggleOne(f.id)} className="flex items-center">
                            {isChecked
                              ? <CheckSquare className="w-3.5 h-3.5 text-orange-500" />
                              : <Square className="w-3.5 h-3.5 text-gray-200 group-hover:text-gray-400 transition-colors" />}
                          </button>
                        </td>

                        {/* Finding ID */}
                        <td className="px-3 py-3 w-28">
                          <span className="font-mono text-[9px] font-bold text-orange-700 bg-orange-50 border border-orange-200 px-1.5 py-0.5 rounded whitespace-nowrap">
                            {fid}
                          </span>
                        </td>

                        {/* Title + badges */}
                        <td className="px-3 py-3 max-w-[220px] cursor-pointer" onClick={() => setDetailId(isDetail ? null : f.id)}>
                          <div className="flex items-start gap-2">
                            <div className={cn("relative flex-shrink-0 mt-1", isCrit && "al-sonar-dot")}>
                              <div className={cn("w-2 h-2 rounded-full", SEV_DOT[f.severity] ?? "bg-gray-300")} />
                            </div>
                            <div className="min-w-0">
                              <div className="text-[11px] font-semibold text-gray-800 leading-tight truncate" title={f.title}>{f.title}</div>
                              <div className="flex items-center gap-1 mt-0.5 flex-wrap">
                                <span className={cn("px-1.5 py-0.5 text-[8px] font-bold rounded-full border uppercase", SEV_BADGE[f.severity])}>{f.severity}</span>
                                {f.kev && <span className="px-1 py-0.5 bg-red-600 text-white rounded text-[7px] font-black">KEV</span>}
                                {f.exploit_available && <span className="px-1 py-0.5 bg-amber-100 text-amber-800 border border-amber-200 rounded text-[7px] font-bold">EXP</span>}
                                {f.mitre_technique && <span className="font-mono text-[8px] text-indigo-600">{f.mitre_technique}</span>}
                              </div>
                            </div>
                          </div>
                        </td>

                        {/* Category */}
                        <td className="px-3 py-3">
                          <span className={cn("px-2 py-0.5 rounded-full border text-[8px] font-semibold whitespace-nowrap", cat.bg, cat.color)}>
                            {cat.label}
                          </span>
                        </td>

                        {/* Score */}
                        <td className="px-3 py-3 w-24">
                          <div className="flex items-center gap-1.5">
                            <div className="w-10 h-1.5 bg-gray-100 rounded-full overflow-hidden">
                              <div className={cn("h-full rounded-full al-bar-fill", score >= 8 ? "bg-red-500" : score >= 6 ? "bg-amber-500" : "bg-blue-400")}
                                style={{ width: `${Math.min(100, score * 10)}%` }} />
                            </div>
                            <span className={cn("text-[10px] font-black tabular-nums", score >= 8 ? "text-red-600" : score >= 6 ? "text-amber-600" : "text-blue-600")}>{score.toFixed(1)}</span>
                          </div>
                        </td>

                        {/* Status */}
                        <td className="px-3 py-3">
                          {sc && <span className={cn("px-2 py-0.5 text-[8px] font-bold rounded-full border whitespace-nowrap", sc.badge)}>{sc.label}</span>}
                        </td>

                        {/* SLA */}
                        <td className="px-3 py-3 w-24">
                          {f.sla_status ? (
                            <span className={cn("px-2 py-0.5 text-[8px] font-bold rounded-full border whitespace-nowrap",
                              f.sla_status === "breached" ? "bg-red-50 text-red-700 border-red-300 al-heartbeat" :
                              f.sla_status === "warning"  ? "bg-amber-50 text-amber-700 border-amber-200" :
                              "bg-green-50 text-green-700 border-green-200")}>
                              {f.sla_status}
                            </span>
                          ) : <span className="text-gray-200 text-[9px]">—</span>}
                        </td>

                        {/* Assignee */}
                        <td className="px-3 py-3">
                          {f.assignee
                            ? <div className="flex items-center gap-1"><div className="w-4 h-4 rounded-full bg-orange-100 flex items-center justify-center text-[7px] font-black text-orange-600 flex-shrink-0">{f.assignee[0].toUpperCase()}</div><span className="text-[9px] text-gray-600 truncate max-w-[80px]">{f.assignee}</span></div>
                            : <span className="text-[9px] text-amber-500 font-semibold flex items-center gap-0.5"><User className="w-2.5 h-2.5" />Unassigned</span>}
                        </td>

                        {/* Agent */}
                        <td className="px-3 py-3 text-[9px] font-mono text-gray-400">{f.agent_id?.slice(0, 12)}</td>

                        {/* Time */}
                        <td className="px-3 py-3 text-[9px] text-gray-400 whitespace-nowrap">
                          <div>{relTime(f.first_detected_at)}</div>
                          <div className="text-gray-300">seen {f.scan_count}×</div>
                        </td>

                        {/* Quick actions — visible on row hover */}
                        <td className="pr-2 py-2.5 w-[120px]">
                          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            {(() => {
                              const isActing = quickActing === f.id;
                              const isClosed = ["closed","false_positive","accepted_risk","duplicate"].includes(f.status);
                              if (isClosed) {
                                return (
                                  <button
                                    onClick={e => { e.stopPropagation(); quickAct(f.id, "reopen"); }}
                                    disabled={isActing || !can("update_finding")}
                                    title="Reopen finding"
                                    className="flex items-center gap-1 px-2 py-1 rounded-lg text-[9px] font-bold bg-blue-50 text-blue-700 border border-blue-200 hover:bg-blue-100 transition-colors disabled:opacity-50 whitespace-nowrap"
                                  >
                                    <RotateCcw className="w-2.5 h-2.5" />
                                    {isActing ? "…" : "Reopen"}
                                  </button>
                                );
                              }
                              return (
                                <>
                                  <button
                                    onClick={e => { e.stopPropagation(); quickAct(f.id, "close"); }}
                                    disabled={isActing || !can("update_finding")}
                                    title="Close finding"
                                    className="flex items-center gap-1 px-2 py-1 rounded-lg text-[9px] font-bold bg-green-50 text-green-700 border border-green-200 hover:bg-green-100 transition-colors disabled:opacity-50 whitespace-nowrap"
                                  >
                                    <CheckCircle2 className="w-2.5 h-2.5" />
                                    {isActing ? "…" : "Close"}
                                  </button>
                                  <button
                                    onClick={e => { e.stopPropagation(); quickAct(f.id, "accept-risk"); }}
                                    disabled={isActing || !can("update_finding")}
                                    title="Accept risk"
                                    className="flex items-center gap-1 px-2 py-1 rounded-lg text-[9px] font-bold bg-amber-50 text-amber-700 border border-amber-200 hover:bg-amber-100 transition-colors disabled:opacity-50 whitespace-nowrap"
                                  >
                                    <Shield className="w-2.5 h-2.5" />
                                    {isActing ? "…" : "Accept"}
                                  </button>
                                  <button
                                    onClick={e => { e.stopPropagation(); quickAct(f.id, "false-positive"); }}
                                    disabled={isActing || !can("update_finding")}
                                    title="Mark false positive"
                                    className="flex items-center gap-1 px-2 py-1 rounded-lg text-[9px] font-bold bg-gray-50 text-gray-500 border border-gray-200 hover:bg-gray-100 transition-colors disabled:opacity-50 whitespace-nowrap"
                                  >
                                    <XCircle className="w-2.5 h-2.5" />
                                    FP
                                  </button>
                                </>
                              );
                            })()}
                          </div>
                        </td>

                        {/* Expand */}
                        <td className="pr-3 py-3 w-6 text-gray-300 cursor-pointer" onClick={() => setDetailId(isDetail ? null : f.id)}>
                          {isDetail ? <ChevronDown className="w-3.5 h-3.5 text-orange-400" /> : <ChevronRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Footer + Pagination */}
          {sorted.length > 0 && (
            <div className="border-t border-gray-100 bg-gray-50/60">
              {/* Summary row */}
              <div className="px-5 py-2 flex items-center justify-between text-[10px] border-b border-gray-100">
                <div className="flex items-center gap-3">
                  <span className="font-bold text-gray-700">
                    Showing <span className="text-orange-600">{pageStart}–{pageEnd}</span> of <span className="text-gray-900">{sorted.length}</span> findings
                    {sorted.length !== total && <span className="text-gray-400 ml-1">(filtered from {total})</span>}
                  </span>
                  {critical > 0    && <span className="text-red-600 font-bold flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />{critical} critical</span>}
                  {slaBreached > 0 && <span className="text-red-500 font-bold">{slaBreached} SLA breach</span>}
                  {unassigned > 0  && <span className="text-amber-600 font-semibold">{unassigned} unassigned</span>}
                </div>
                <div className="text-gray-400">
                  {selected.size > 0
                    ? <span className="text-orange-500 font-bold">{selected.size} selected across all pages · bulk actions above</span>
                    : "Click row to open case · ☐ to select"}
                </div>
              </div>

              {/* Pagination controls */}
              <div className="px-5 py-2.5 flex items-center justify-between">
                {/* Prev */}
                <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}
                  className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-semibold rounded-xl border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-all">
                  ← Prev
                </button>

                {/* Page chips */}
                <div className="flex items-center gap-1">
                  {Array.from({ length: totalPages }, (_, i) => {
                    const show = i === 0 || i === totalPages - 1 || Math.abs(i - page) <= 1;
                    const ellipsisBefore = i === 2 && page > 3;
                    const ellipsisAfter  = i === totalPages - 3 && page < totalPages - 4;
                    if (!show) {
                      if (ellipsisBefore || ellipsisAfter)
                        return <span key={`e${i}`} className="text-[10px] text-gray-400 px-1">…</span>;
                      return null;
                    }
                    return (
                      <button key={i} onClick={() => setPage(i)}
                        className={cn(
                          "w-7 h-7 rounded-lg text-[10px] font-bold transition-all border",
                          page === i
                            ? "bg-orange-500 text-white border-orange-500 shadow-sm"
                            : "bg-white text-gray-600 border-gray-200 hover:bg-orange-50 hover:border-orange-200 hover:text-orange-600"
                        )}>
                        {i + 1}
                      </button>
                    );
                  })}
                </div>

                {/* Next */}
                <button onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))} disabled={page === totalPages - 1}
                  className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-semibold rounded-xl border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-all">
                  Next →
                </button>
              </div>
            </div>
          )}
      </div>{/* end table card */}

      {/* Fixed right-side drawer — rendered outside page flow */}
      {detailFinding && (
        <FindingDetailPanel
          finding={detailFinding}
          onClose={closeDetail}
          onRefresh={load}
          canEdit={can("update_finding")}
        />
      )}
    </div>
  );
}
