#!/usr/bin/env bash
# =============================================================================
#  agent/build.sh — Build the unified attacklens-agent binary
#
#  Produces a single self-contained executable via PyInstaller.
#  No separate install scripts or helper files are needed — the binary itself
#  handles install, run, start, stop, status, reload, uninstall, and logs.
#
#  Usage:
#    bash agent/build.sh                          # auto-detect platform + arch
#    bash agent/build.sh --version 1.2.0          # set version string
#    bash agent/build.sh --manager http://IP:8080  # bake in manager URL (optional)
#    bash agent/build.sh --arch x86_64             # cross-arch hint (macOS only)
#    bash agent/build.sh --clean                   # remove previous build artefacts first
#
#  Output:
#    agent/dist/attacklens-agent          (macOS / Linux)
#    agent/dist/attacklens-agent.exe      (Windows)
#
#  After building:
#    sudo dist/attacklens-agent install --manager http://YOUR_MANAGER:8080
# =============================================================================
set -euo pipefail

# ── Args ──────────────────────────────────────────────────────────────────────
VERSION="${VERSION:-1.2.0}"
MANAGER_URL="${MANAGER_URL:-}"
ARCH="${ARCH:-}"
CLEAN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)  VERSION="$2";     shift 2 ;;
    --manager)  MANAGER_URL="$2"; shift 2 ;;
    --arch)     ARCH="$2";        shift 2 ;;
    --clean)    CLEAN=1;          shift   ;;
    *)          echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIST_DIR="${SCRIPT_DIR}/dist"
BUILD_DIR="${SCRIPT_DIR}/build"

# ── Detect Python ─────────────────────────────────────────────────────────────
PYTHON3=""
for p in python3.13 python3.12 python3.11 python3 \
          /usr/local/bin/python3 /opt/homebrew/bin/python3; do
  if command -v "$p" &>/dev/null; then PYTHON3="$p"; break; fi
done
[[ -z "$PYTHON3" ]] && { echo "ERROR: python3 not found" >&2; exit 1; }
PYTHON_VER=$("$PYTHON3" --version 2>&1)

# ── Platform / output name ────────────────────────────────────────────────────
OS_NAME=$(uname -s)
MACHINE=$(uname -m)
[[ -n "$ARCH" ]] && MACHINE="$ARCH"

case "$OS_NAME" in
  Darwin)  PLATFORM="macos";   EXT="";     PKG_ARCH="${MACHINE}" ;;
  Linux)   PLATFORM="linux";   EXT="";     PKG_ARCH="${MACHINE}" ;;
  MINGW*|MSYS*|CYGWIN*) PLATFORM="windows"; EXT=".exe"; PKG_ARCH="x86_64" ;;
  *)       PLATFORM="unknown"; EXT=""  ;;
esac

BINARY_NAME="attacklens-agent${EXT}"
DIST_BINARY="${DIST_DIR}/${BINARY_NAME}"

echo ""
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║   AttackLens Agent — Unified Build        ║"
echo "  ╚═══════════════════════════════════════════╝"
echo ""
echo "  Version  : ${VERSION}"
echo "  Platform : ${PLATFORM} / ${MACHINE}"
echo "  Python   : ${PYTHON3} (${PYTHON_VER})"
echo "  Output   : ${DIST_BINARY}"
[[ -n "$MANAGER_URL" ]] && echo "  Manager  : ${MANAGER_URL} (baked in)"
echo ""

# ── Clean ─────────────────────────────────────────────────────────────────────
if [[ "$CLEAN" -eq 1 ]]; then
  echo "  Cleaning previous build..."
  rm -rf "${BUILD_DIR}" "${DIST_DIR}"
fi

# ── Ensure PyInstaller ────────────────────────────────────────────────────────
"$PYTHON3" -c "import PyInstaller" 2>/dev/null \
  || "$PYTHON3" -m pip install pyinstaller --quiet

# ── Write version + optional baked-in manager URL ────────────────────────────
VERSION_FILE="${SCRIPT_DIR}/_build_version.py"
cat > "${VERSION_FILE}" <<PYEOF
# Auto-generated by build.sh — do not edit
__version__ = "${VERSION}"
BAKED_MANAGER_URL = "${MANAGER_URL}"
PYEOF

# ── Collect hidden imports ────────────────────────────────────────────────────
# All collector modules must be explicitly listed because PyInstaller cannot
# discover them through the dynamic plugin loader in core.py.

HIDDEN=(
  # macOS collectors
  "agent.os.macos.collectors.volatile"
  "agent.os.macos.collectors.network"
  "agent.os.macos.collectors.system"
  "agent.os.macos.collectors.posture"
  "agent.os.macos.collectors.inventory"
  "agent.os.macos.collectors.developer_security"
  "agent.os.macos.normalizer"
  "agent.os.macos.keystore"
  "agent.os.macos.launchd"
  # Windows collectors
  "agent.os.windows.collectors"
  "agent.os.windows.service"
  "agent.os.windows.normalizer"
  # Linux collectors
  "agent.os.linux.normalizer"
  # Core modules
  "agent.agent.core"
  "agent.agent.sender"
  "agent.agent.crypto"
  "agent.agent.enrollment"
  "agent.agent.watchdog"
  "agent.selfinstall"
  # Standard / third-party
  "psutil"
  "tomllib"
)

HIDDEN_ARGS=()
for mod in "${HIDDEN[@]}"; do
  HIDDEN_ARGS+=("--hidden-import=${mod}")
done

# tomli fallback for Python < 3.11
"$PYTHON3" -c "import tomllib" 2>/dev/null \
  || HIDDEN_ARGS+=("--hidden-import=tomli")

# ── Run PyInstaller ───────────────────────────────────────────────────────────
cd "${REPO_ROOT}"

"$PYTHON3" -m PyInstaller \
  --onefile \
  --name "attacklens-agent" \
  --distpath "${DIST_DIR}" \
  --workpath "${BUILD_DIR}" \
  --specpath "${BUILD_DIR}" \
  --paths "${REPO_ROOT}" \
  "${HIDDEN_ARGS[@]}" \
  --collect-submodules agent \
  --noconfirm \
  --log-level WARN \
  "agent/agent_entry.py"

# ── Verify ────────────────────────────────────────────────────────────────────
if [[ ! -f "${DIST_BINARY}" ]]; then
  echo "  ERROR: build produced no binary at ${DIST_BINARY}" >&2
  exit 1
fi

BINARY_SIZE=$(du -sh "${DIST_BINARY}" | awk '{print $1}')

echo ""
echo "  ✓ Build complete"
echo ""
echo "  Binary : ${DIST_BINARY}  (${BINARY_SIZE})"
echo ""
echo "  ── Quick start ──────────────────────────────────────────────────"
echo "    sudo ${DIST_BINARY} install --manager http://YOUR_MANAGER:8080"
echo "    ${DIST_BINARY} status"
echo "    ${DIST_BINARY} logs"
echo "    sudo ${DIST_BINARY} uninstall"
echo ""
echo "  ── Dev / source run (no install) ───────────────────────────────"
echo "    ${DIST_BINARY} run --config agent.toml"
echo ""

# ── Cleanup temp version file ─────────────────────────────────────────────────
rm -f "${VERSION_FILE}"
