"""
manager/manager/api/enroll.py — POST /api/v1/enroll

Agent enrollment endpoint.

The agent generates its own 256-bit API key and sends it here on first run,
authenticated with a one-time enrollment token configured on the manager side.
The manager records the agent_id → api_key mapping in SQLite; all subsequent
ingest requests are authenticated with HMAC derived from that per-agent key.

Security model
──────────────
  • The enrollment token is a shared secret configured by the operator in
    manager.conf [auth] enrollment_tokens. It is NOT the API key itself.
  • The token is sent over TLS 1.3 in the X-Enrollment-Token header.
  • The API key is generated by the agent (not the manager) so a compromised
    enrollment token does not reveal an existing agent's session key.
  • Re-enrollment (key rotation) is allowed: the old key is replaced.
  • The endpoint is intentionally unauthenticated beyond the token check so
    new agents can register before they have a valid API key.
"""
from __future__ import annotations

import logging
import time

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

log = logging.getLogger("manager.enroll")

_HEX_CHARS = frozenset("0123456789abcdef")


class EnrollRequest(BaseModel):
    agent_id:   str
    agent_name: str
    api_key:    str    # 64 hex chars (256-bit key generated by agent)
    hostname:   str
    os:         str
    arch:       str
    timestamp:  int


def make_enroll_router(db, enrollment_tokens: list[str]) -> APIRouter:
    """
    Factory that binds the enrollment router to the shared DB and the
    operator-configured list of valid enrollment tokens.
    """
    router = APIRouter()

    @router.post("/enroll")
    async def enroll(req: Request, body: EnrollRequest):
        # ── Token check ───────────────────────────────────────────────────────
        token = req.headers.get("X-Enrollment-Token", "").strip()
        client_ip = req.client.host if req.client else "unknown"

        if not token or token not in enrollment_tokens:
            log.warning(
                "Enrollment rejected: invalid token from %s (agent_id=%s)",
                client_ip, body.agent_id,
            )
            raise HTTPException(status_code=401, detail="Invalid enrollment token")

        # ── Validate key format ───────────────────────────────────────────────
        key = body.api_key.lower()
        if len(key) != 64 or not all(c in _HEX_CHARS for c in key):
            raise HTTPException(
                status_code=400,
                detail="api_key must be exactly 64 lowercase hex characters (256-bit)",
            )

        # ── Validate agent_id ─────────────────────────────────────────────────
        agent_id = body.agent_id.strip()
        if not agent_id or len(agent_id) > 128:
            raise HTTPException(status_code=400, detail="Invalid agent_id")

        # ── Timestamp skew check (prevents delayed replay of enrollment) ──────
        skew = abs(time.time() - body.timestamp)
        if skew > 300:
            raise HTTPException(status_code=400, detail="Timestamp out of range")

        # ── Store key + upsert agent ──────────────────────────────────────────
        is_rotation = (await db.get_agent_key(agent_id)) is not None
        await db.upsert_agent_key(agent_id, key, enrolled_ip=client_ip)
        await db.upsert_agent(agent_id, body.agent_name, client_ip)

        action = "re-enrolled (key rotation)" if is_rotation else "enrolled"
        log.info(
            "Agent %s: agent_id=%s os=%s arch=%s hostname=%s ip=%s",
            action, agent_id, body.os, body.arch, body.hostname, client_ip,
        )

        return {"ok": True, "agent_id": agent_id, "rotated": is_rotation}

    return router
